OCManager/Controllers/FormController.cs
using OCManager.Entities.DBEntities;
using System;
using System.Collections.Generic;
using OCManager.Interface.BusinessInterface;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ninject;
using OCManager.Entities.Anonymous;
using System.Net;
using System.Text;
using System.IO;
using SelectPdf;
using System.Globalization;
using HtmlAgilityPack;
using System.Text.RegularExpressions;
using System.Windows.Forms;

namespace OCManager.Controllers
{
    [Authorize]
    public class FormController : Controller
    {
        [Inject]
        public IFormBusinessService _FormBusinessService { get; set; }

        [Inject]
        public IOccurenceBusinessService _occurenceBusinessService { get; set; }
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Form1464314(int patID)
        {
            Form1464314 frm = new Form1464314();
            ViewBag.PatID = patID;
            return View(frm);
        }
        [HttpPost]
        public ActionResult Form1464314(Form1464314 frm)
        {
            frm.Username = User.Identity.GetUserName();
            frm.User_Id = Convert.ToInt32(Session["userID"]);
            frm.Data = DateTime.Now;
            int patID = Convert.ToInt32(Request.Form["patID"]);
            _FormBusinessService.SaveForm1464314(frm, patID);
            return View();
        }

        // [AllowAnonymous]
        [HttpGet]      
        public ActionResult Form1247857(int patID, int? formDataId, int? isPdf)
        {
            var procedureList = _FormBusinessService.GetProcedureListByFormID(1247857);
            if (formDataId > 0)
            {
                List<storage_string> lstFrmData = _FormBusinessService.GetStorageStrinfFormData(formDataId.Value);
                ViewBag.SS = lstFrmData;
                if (isPdf != null)
                {
                    ViewBag.isPDF = 1;
                    foreach (var item in lstFrmData)
                    {
                        if (!String.IsNullOrEmpty(item.value_Key) && Char.IsNumber(item.value_Key[0]))
                        {
                            string name = item.value_Key.Substring(0, item.value_Key.IndexOf("цена"));
                            name = name.Substring(name.IndexOf(' '), name.Length - 2).Trim();
                            var obj = procedureList.FirstOrDefault(p => p.Name.Contains(name));
                            obj.Name = Convert.ToString(obj.Name + "_" + item.value);
                        }
                        else if (item.value_Key == "Итог")
                        {
                            ViewBag.tot = item.value;
                        }
                        else if (item.value_Key == "Скидки :")
                        {
                            ViewBag.DiscountBonus = double.Parse(item.value.Replace(',', '.'), CultureInfo.InvariantCulture);
                        }
                        else if (item.value_Key == "Добавления к цене :")
                        {
                            ViewBag.DiscountIncrease = double.Parse(item.value.Replace(',', '.'), CultureInfo.InvariantCulture);
                        }
                        else if(item.value_Key == "Дата")
                        {
                            ViewBag.data = item.value.Split(' ')[0];
                        }
                    }
                }
            }
            ViewBag.Discount = _FormBusinessService.GetDiscountList();

            int DiscountCalc = _FormBusinessService.FetchDiscountCalculation(patID);
            if (DiscountCalc < 40000)
            {
                ViewBag.GetDiscountBySpend = 0;
            }
            else if (DiscountCalc > 40000 && DiscountCalc < 70000)
            {
                ViewBag.GetDiscountBySpend = 1;
            }
            else
            {
                ViewBag.GetDiscountBySpend = 2;
            }
            ViewBag.patID = patID;
            return View(procedureList);
        }

        //This function saves both forms 1247857 and 2161884
        [HttpPost]
        public ActionResult saveFormValues(List<storage_string> items, string total, int frmID, int? formDataID, int patID, DateTime dateSelected)
        {
            int userID = Convert.ToInt32(Session["userID"]);
            int res = 1;
            if (frmID == 1247857)
            {
                res = _FormBusinessService.CheckAttendaceDate(patID, dateSelected);
            }
            int frmDataID = 0;
            if (res == 1)
                frmDataID = _FormBusinessService.SaveForm1247857(items, total, userID, frmID, formDataID, dateSelected);
            else
                formDataID = res;
            return Json(frmDataID, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult saveIndex(List<string> vals)
        {
            _FormBusinessService.SaveOrderIndex(vals);
            //return View();
            //return Json("output", JsonRequestBehavior.AllowGet);
            return Json(1, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ConfigureForm1247857(int ID)
        {
            var procedureList = _FormBusinessService.GetProcedureListByFormID(1247857);
            return View(procedureList);
        }
        [HttpPost]
        public ActionResult ConfigureForm1247857(List<Appointment> lstApp, List<string> vals)
        {
            _FormBusinessService.SaveBaseForm1247857(lstApp);
            return Json(1, JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        //public ActionResult Form2161884(int patID, bool main)
        //{
        //    Form_2161884DTO obj = _FormBusinessService.GetForm2061884Data();
        //    ViewBag.Discount = _FormBusinessService.GetDiscountList();
        //    ViewBag.PatID = patID;
        //    return View(obj);
        //}

        [HttpGet]
        public ActionResult Form2161884(int patID)
        {
            Form_2161884DTO obj = _FormBusinessService.GetForm2061884Data();
            ViewBag.Discount = _FormBusinessService.GetDiscountList();
            var blist = _occurenceBusinessService.GetAllBuildings().Select(a =>
            new SelectListItem { Text = a.Name, Value = Convert.ToString(a.ID) });
            ViewBag.BuildingList = blist;
            ViewBag.PatID = patID;
            return View(obj);
        }

        [HttpPost]
        public ActionResult SavePatientInHealing(PatientInHealing objData)
        {
            objData.Form_Filling_Date = DateTime.Now;
            objData.Who_Filled_Username = User.Identity.Name;
            objData.Who_Filled_Nickname = "";
            _FormBusinessService.SavePatHeiling(objData);
            return Json(1, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Form2161884(Form_2161884DTO obj, int patID)
        {
            obj.data = DateTime.Now;
            obj.user_id = Convert.ToInt32(Session["userID"]);
            obj.username = User.Identity.Name;
            int frmDataID = _FormBusinessService.Save2161884(obj, patID);
            return Json(frmDataID, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult Form1242785(int patID, string from, string to, string isAll) //, string formDataID)
        {
            //Form1242785 relForm = null;
            if (Session["IsOperator"] != null)
            {
                ViewBag.docList = _FormBusinessService.GetDoctorList();
            }
            else
            {
                //relForm = _FormBusinessService.CheckReleaseFormAssignee(patID);
                int perID = Convert.ToInt32(Session["perID"]);
                
                Form1242785 releaseFormData = _FormBusinessService.GetReleaseFormData(patID, Convert.ToInt32(Session["userID"]));
                if (releaseFormData.NextAssignee == "Completed")
                {
                    ViewBag.Assignee = "completed";
                    return View(releaseFormData);
                }
                string GeneralPatientGeneralInfo = _FormBusinessService.GetPatientInfo(patID);
                string generalInfo = "\n <center><h3>Выписка из амбулаторной карты № " + GeneralPatientGeneralInfo.Split('_')[0] + System.Environment.NewLine +
                 GeneralPatientGeneralInfo.Split('_')[1] + " " + GeneralPatientGeneralInfo.Split('_')[2] + "</h3> </center> <hr> ";
                generalInfo = generalInfo + "Пациент: " + GeneralPatientGeneralInfo.Split('_')[1] + " " + GeneralPatientGeneralInfo.Split('_')[2] + System.Environment.NewLine;
                generalInfo = generalInfo + " Дата рождения: " + GeneralPatientGeneralInfo.Split('_')[3] + System.Environment.NewLine;
                generalInfo = generalInfo + " Находится на амбулаторном обследовании и лечении в КО ЦОЗДиП «Ясный Взор» с ";
                if(isAll == "1")
                {
                    generalInfo = generalInfo + GeneralPatientGeneralInfo.Split('_')[4] ;
                }
                else
                {
                    generalInfo = generalInfo + from ;
                }
                
                Console.WriteLine(generalInfo);
                if (perID == Convert.ToInt32(releaseFormData.NextAssignee) && releaseFormData.Tekst_Vipiski_0 != null)
                {
                    string RegexPattern = "navbar-fixed-top";
                    releaseFormData.Tekst_Vipiski_0 = Regex.Replace(releaseFormData.Tekst_Vipiski_0, "</head>", "<style>.hideHeader{display: none;}</style></head>");
                    releaseFormData.Tekst_Vipiski_0 = Regex.Replace(releaseFormData.Tekst_Vipiski_0, RegexPattern, "hideHeader");
                    ViewBag.stringData = generalInfo + releaseFormData.Tekst_Vipiski_0;
                    ViewBag.PatID = patID;
                    return View(releaseFormData);
                }

OCManager/Views/Form/Form1242785.cshtml
@using OCManager.Entities.Anonymous;
@model OCManager.Entities.DBEntities.Form1242785

@{
    ViewBag.Title = "";
}

<style>
    .richText {
        height: 600px;
    }
</style>
@if (Session["IsOperator"] != null)
{
    if (Convert.ToInt32(Session["IsOperator"]) == 1)
    {
        <h3>Выписка</h3>
        <p>
            Вы можете заказать составление выписки.<br>
            Для этого, пожалуйста, выберите тип выписки и доктора, который её составит.<br>
        </p>
        <div class="row">
            <label class="control-label col-sm-2" for="doctors">Врач:</label>
            <div style="width:40%" class="col-md-10">
                @Html.DropDownList("docDDL", ((List<Doctors>)ViewBag.docList).Select(m => new SelectListItem { Text = m.Name, Value = Convert.ToString(m.Email) }),
                                new { @class = "selectpicker" })
            </div>
        </div>
        <div class="row">
            <p>выберите тип выписки ↓</p>
            <input type="radio" name="tip_vipiski" value="1">
            <lable class="tv_l_1">за 1-2 курса лечения</lable>
            <small class="tv_s_1">(срок изготовления 3 рабочих дня)</small>
            <br />
            <input type="radio" name="tip_vipiski" value="2">
            <lable class="tv_l_2">за последний год наблюдений</lable>
            <small class="tv_s_2"> (срок изготовления 3 рабочих дня)</small>
            <br />
            <input type="radio" name="tip_vipiski" value="3">
            <lable class="tv_l_3">за весь период наблюдения </lable>
            <small class="tv_s_3">(срок изготовления 5 рабочих дней)</small>
            <br />

            <strong>Ваши комментарии (примечания) к заказываемой выписке↓</strong>
            <small>Будут включены в email-уведомление для доктора, которому Вы заказываете составление выписки</small>
            <br />
            <textarea class="note_to_order" id="txtareaComment" style="width:500px; height:50px;"></textarea>
        </div>
        <input type="button" id="btnRelease" onclick="AssignReleaseForm()" value="Assign" />
    }
}
else
{
    if (ViewBag.Assignee != null)
    {
        string assignee = Convert.ToString(ViewBag.Assignee);
        if (assignee.Contains("completed"))
        {
            <br />
            <br />
            <p>  Release document for this patient has been completed</p>
        }

        else if (ViewBag.Assignee != "1" && ViewBag.Assignee != null)
        {
            <br />
            <br />
            <p> Release document for this patient has been assigned to @ViewBag.Assignee</p>
        }
    }
    else
    {
        if (Model.Signature_Status == 0 && ViewBag.stringData == null)
        {
            <div id="dvFilter" class="form-horizontal mainForm">
                <h4>Выписка</h4>
                <hr />

                <div class="row">
                    Вы можете ↓

                    <div>
                        <input type="button" value="Сформировать выписку за весь период" id="btnWholePeriod" onclick="getAllFormData();" />
                    </div>
                    @*<div>
                        <input type="button" value="View Pdf" id="btnPrintPdf" onclick="printPDF();" />
                    </div>*@

                </div>
                <div class="row">
                    или ↓
                    <div>
                        <input type="button" value="Сформировать выписку за указанный период" onclick="getFormDataRange();" id="btnRange" />
                        с  <input class="Calendar" type="text" value="@ViewBag.fdate" data-date-format="dd-mm-yyyy" id="fromDate" name="fromDate" />
                        по <input class="Calendar" type="text" id="toDate" value="@ViewBag.tdate" data-date-format="dd-mm-yyyy" name="toDate" />
                    </div>

                </div>

            </div>
        }
        else
        {
            <div id="dvData" class="row">
                @{
                    if (Model.Tip_Vipiski == 1)
                    {
                        <span>
                            Составление этой выписки за 1 - 2 курса лечения заказано
                            пользователем @Model.Username.Split('_')[0] доктору Диагностика @Model.Username.Split('_')[1]
                        </span>
                    }
                    else if (Model.Tip_Vipiski == 2)
                    {
                        <span>
                            Составление этой выписки за 1 - 2 курса лечения заказано
                            пользователем @Model.Username.Split('_')[0] доктору Диагностика @Model.Username.Split('_')[1]
                        </span>
                    }
                    else
                    {
                        <span>
                            Составление этой выписки за 1 - 2 курса лечения заказано
                            пользователем @Model.Username.Split('_')[0] доктору Диагностика @Model.Username.Split('_')[1]
                        </span>
                    }
                }
            </div>
            <div class="row">
                срок изготовления 3 рабочих дня
            </div>
            <div class="row">
                дата заказа выписки <b> @Model.create_date </b>
            </div>
            <br />
            <div class="row">
                Примечание к заказанной выписке: <br />
                @Model.Comment
            </div>
            <div class="row">
                <input type="button" value="View Pdf" id="btnPrintPdf" onclick="printPDF();" />
            </div>
            <div id="dvData" class="row">
                <textarea class="richText" id="richText">
                    @if (Model.Tekst_Vipiski_0 == null)
                    {
                        <img src="~/Content/ReleaseDoc/wapka-kaliningrad.jpg" alt="" />
                    }
                    @Html.Raw(ViewBag.stringData)
                </textarea>
            </div>
            <input type="hidden" id="hdnSigStatus" name="hdnSigStatus" value="@Model.Signature_Status" />
                    if (Model.Signature_Status == 0)
                    {
                        <div class="row" style="padding-top:3%">
                            <div class="form-group">
                                Заведующий отделением
                                @Html.DropDownList("head1", new List<SelectListItem>()
                        {
                            new SelectListItem(){ Text= "-", Value = "0"},
                            new SelectListItem(){ Text= "Ляо И.В.", Value = "669148"},
                            new SelectListItem(){ Text= "Никитина А.А.", Value = "797236"},
                            new SelectListItem(){ Text= "Шавердова М.С.", Value = "626557"},
                            new SelectListItem(){ Text= "Кудряшова Е.А.", Value = "2109561"},
                            new SelectListItem(){ Text= "Агагулян С.Г.", Value = "2219738"},
                            new SelectListItem(){ Text= "Узуев М.И.", Value = "2166303"}
                        })

                                Заведующий отделением
                                @Html.DropDownList("head2", new List<SelectListItem>()
                        {
                            new SelectListItem(){ Text= "-", Value = "0"},
                            new SelectListItem(){ Text= "Ляо И.В.", Value = "669148"},
                            new SelectListItem(){ Text= "Никитина А.А.", Value = "797236"},
                            new SelectListItem(){ Text= "Шавердова М.С.", Value = "626557"},
                            new SelectListItem(){ Text= "Кудряшова Е.А.", Value = "2109561"},
                            new SelectListItem(){ Text= "Агагулян С.Г.", Value = "2219738"},
                            new SelectListItem(){ Text= "Узуев М.И.", Value = "2166303"}
                        })
                            </div>
                            @if (Model.Signature_613915 != null)
                            {
                                <div>
                                    И.Э.: <input type="checkbox" checked="checked" id="mainHead" name="mainHead" value="613915" />
                                </div>
                            }
                            else
                            {
                                <div>
                                    И.Э.: <input type="checkbox" id="mainHead" name="mainHead" value="613915" />
                                </div>
                            }
                            @if (Model.Signature_603615 != null)
                            {
                                <div>
                                   В.О.:  <input type="checkbox" checked="checked" id="deputy" name="deputy" value="603615" />
                                </div>
                            }
                            else
                            {
                                <div>
                                    В.О.:  <input type="checkbox" id="deputy" name="deputy" value="603615" />
                                </div>
                            }

                        </div>
                    }
                    else
                    {
                        <p>The document will be signed by: </p>
                        if (Model.Head1 != "0" && Model.Head1 != null)
                        {<div>Заведующий отделением:<label id="lblhead1">@Model.Head1</label></div>}
                        if (Model.Head2 != "0" && Model.Head2 != null)
                        {<div> Заведующий отделением: <label id="lblhead2">@Model.Head2</label></div>}
                        if (Model.Signature_603615 != null)
                        {<div> В.О.: <label id="lblsig1">@Model.Signature_603615</label></div>}
                        if (Model.Signature_613915 != null)
                        {<div> И.Э. :<label id="lblsig2">@Model.Signature_613915</label></div>}
                        
                    }
                    <div>
                        Signed:  <input type="checkbox" id="signed" name="signed" value="1" />
                        <input type="button" id="btnDocSave" onclick="SaveReleaseDoc()" value="Save" />
                        <input type="hidden" id="hdnFormDataID" name="hdnFormDataID" value="@Model.Form_Data_ID" />
                        <input type="hidden" id="hdnDocID" name="hdnDocID" value="@Model.Attending_Doctor" />

                        @if (Model.Signature_Status > 0)
                        {
                            <input type="button" id="btnDocSave" onclick="RejectReleaseDoc()" value="Reject" />
                        }
                    </div>
                            }
                        }
                    }
<input type="hidden" id="hdnPatID" name="hdnPatID" value="@ViewBag.PatID" />

<script src="~/Scripts/tinymce.js"></script>
<script>
    $(document).ready(function () {

        tinymce.init({ mode: "specific_textareas", editor_selector: 'richText',  language : "ru" });

        //$('#fromDate').datepicker("setDate", new Date());
        //$('#toDate').datepicker("setDate", new Date());
    });
</script>

OCManager/Views/Form/Form1247857.cshtml
@using OCManager.Entities.DBEntities;
@model IEnumerable<OCManager.Entities.DBEntities.Appointment>
@{
    ViewBag.Title = "Simple Form";
}
<h2>Назначения по лечению 2012</h2>
<form class="form-horizontal">
    <div style="padding-left:50px;" class="container">
        <div class="row" style="padding-top:30px;">
            <div class="form-group">
                @*@Html.DropDownList("DiscountBonus", (IEnumerable<SelectListItem>)ViewBag.DiscountBonus,
                    "-", new { @class = "selectpicker" })*@
                <label style="width:20%" class="control-label col-sm-2" for="doctors">Добавления к цене :</label>
                @if (ViewBag.isPDF == 1)
                {
                    double di = ViewBag.DiscountIncrease * 100;
                    string ss = Convert.ToString(di) + "%";
                    @ss;
                }
                <div style="width:80%" class="col-md-10">
                    @Html.DropDownList("DiscountIncrease", ((List<Discount>)ViewBag.Discount).Where(a => a.Type == "increase").ToList()
.Select(m => new SelectListItem
{ Text = m.Name, Value = Convert.ToString(m.Value) }), "-",
                 new { @class = "selectpicker test", @onchange = "calculatePrice();" })

                    <div style="width:200px; float:right;">
                        <a style="width:150px;" href="javascript:void(0)"
                           onclick="location.href='@Url.Action("ConfigureForm1247857", "Form",
                          new { id = Request.Url.ToString().Split('=')[1]})'"
                           id="@Request.Url.ToString().Split('=')[1]">Configure Form</a>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <label style="width:20%" class="control-label col-sm-2" for="doctors">Скидки :</label>
                <div style="width:80%" class="col-md-10">
                    @if (ViewBag.isPDF == 1)
                    {
                        double db = ViewBag.DiscountBonus * 100;
                        string ss = Convert.ToString(db) + "%";
                        @ss;
                    }
                    @Html.DropDownList("DiscountBonus", ((List<Discount>)ViewBag.Discount).Where(a => a.Type == "discount" || a.Type == "bonus")
.ToList().Select(m => new SelectListItem
{ Text = m.Name, Value = Convert.ToString(m.Value) }), "-",
                 new { @class = "selectpicker test1", @onchange = "calculatePrice();" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <label style="width:20%" class="control-label col-sm-2" for="date">Дата:</label>
                <div style="width:80%" class="col-md-10">
                    <input type="text" class="form-control Calendar" id="txtDate" data-date-format="dd-mm-yyyy" value="@ViewBag.data">
                </div>
            </div>
        </div>
        <table class="table table-bordered pagin-table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        Кол-во
                    </th>
                </tr>
            </thead>
            <tbody class="connectedSortable">
                @{ int i = 0; }
                @foreach (var item in Model)
                {
                    string selectID = "select" + i;
                    <tr id="@item.ID">
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.ID)
                        </td>
                        @if (item.Type != "title")
                        {
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                        }
                        else
                        {
                            if (item.Name.Contains('_'))
                            {
                                <td style="font-weight:bold">
                                    @item.Name.Split('_')[0];
                                </td>
                            }
                            else
                            {
                                <td style="font-weight:bold">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                            }
                        }
                        @if (item.Type != "title")
                        {
                            if (ViewBag.isPDF == 1)
                            {
                                if (item.Name.Contains('_'))
                                {
                                    <td style="font-weight:bold">
                                        @item.Name.Split('_')[1]
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        <select id="@selectID" class="selectlist" onchange="calculatePrice(this);"></select>
                                    </td>
                                }
                            }
                            else
                            {
                                <td>
                                    <select id="@selectID" class="selectlist" onchange="calculatePrice(this);"></select>
                                </td>
                            }
                        }
                        else
                        {
                            <td></td>
                        }
                        @*<td>
                                @Html.DisplayFor(modelItem => item.Form_ID)
                            </td>*@
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.Cost)
                        </td>
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.Second_Treatment_Discount)
                        </td>
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.story_discount)
                        </td>
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.First_Consult_Bonus)
                        </td>
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.Certificate_Payment)
                        </td>
                        <td style="display:none;">
                            @Html.HiddenFor(modelItem => item.Order)
                        </td>
                    </tr>
                    i++;
                }
                <tr>
                    <td></td>
                    <td>
                        Total: <input type="text" id="tot" name="tot" value="@ViewBag.tot" />
                    </td>

                </tr>
            </tbody>
        </table>
        <div class="row">
            <div>
                <button type="button" onclick="Save1247857(this);" id="btnSave1247857" class="btn btn-default">Save</button>
            </div>
            <input type="hidden" id="hdnFdID" name="hdnFdID" value="" />
            <input type="hidden" id="hdnPatID" name="hdnPatID" value="@ViewBag.patID" />

        </div>
    </div>
</form>
<script type="text/javascript">



    jQuery(function () {
        var selectList = {
            "0": "-",
            "1": "1",
            "2": "2",
            "3": "3",
            "4": "4",
            "5": "5",
            "6": "6",
            "7": "7",
            "8": "8",
            "9": "9",
            "10": "10",
            "11": "11",
            "12": "12",
            "13": "13",
            "14": "14",
            "15": "15",
            "16": "16",
            "17": "17",
            "18": "18",
            "19": "19",
            "20": "20"
        };

        if(@ViewBag.GetDiscountBySpend == 1)
        {
            $('select[name=DiscountBonus] option').eq(4).prop('selected', true).trigger('change');
        }
        else if(@ViewBag.GetDiscountBySpend ==2 )
        {
            $('select[name=DiscountBonus] option').eq(5).prop('selected', true).trigger('change');
        }


        var count = 0;
        $('.selectlist').each(function () {
            $.each(selectList, function (val, text) {
                $("#select" + count).append($('<option />', {
                    value: val,
                    text: text
                }));

            });
            // alert(count);
            count++;
        });

        var sSList = @Html.Raw(Json.Encode(ViewBag.SS));
        $("#hdnFdID").val(sSList[1].foreign_Key);
        for(var i = 0; i < sSList.length; i++) {
            if(sSList[i].value_Key  == "Итог")
            {
                $("#tot").val(sSList[i].value);
            }
            if(sSList[i].value_Key  == "Дата")
            {
                $("#txtDate").val(sSList[i].value.split(' ')[0].replace('.','-'));
            }
            if(sSList[i].value_Key  == "Скидки :")
            {
                $('select[name=DiscountBonus]').val(sSList[i].value).prop('selected', true).trigger('change');
            }
            if(sSList[i].value_Key  == "Добавления к цене :")
            {
                $('select[name=DiscountIncrease]').val(sSList[i].value).prop('selected', true).trigger('change');
            }
            if(sSList[i].value_Key.indexOf('кол') > 0)
            {
                var text = sSList[i].value_Key.split('цена')[0];
                text =  text.substring(text.indexOf(' ')+1);
                $("td:contains(" + text.trim() + ")" ).next().find('select').val(sSList[i].value);
            }
        }

        //$(".txtDate").datepicker();        
        //$('#txtDate').datepicker().on('show', function (e) {
        //    forceParse: false
        //});
    });



</script>